<?php

namespace Administration\AdministrationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FiltreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiltreRepository extends EntityRepository
{
}
