<?php

namespace Administration\AdministrationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends EntityRepository
{
    public function getNb() {

        return $this->createQueryBuilder('p')

            ->select('COUNT(p)')

            ->getQuery()

            ->getSingleScalarResult();

    }

    public function findAllOrdre() {

        $req = $this->createQueryBuilder('p')


            ->select('p')
            ->orderBy('p.dateRecette','ASC');


        return $req->getQuery()->getResult();



    }

    public function recherche($recherche){
        $req = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.nomRecette like :recherche')
            ->orderBy('p.id')
            ->setParameter('recherche', '%'.$recherche.'%');
        return $req->getQuery()->getResult();
    }


}
