<?php

namespace Administration\AdministrationBundle\Repository;

/**
 * TypeCuissonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCuissonRepository extends \Doctrine\ORM\EntityRepository
{
}
