fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

projet:
    resource: "@ProjetBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /administration

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
