# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    redirect.after.login:
        class: Client\ClientBundle\Redirection\AfterLoginRedirection
        arguments: [@router]
