ambiance_index:
    path:     /
    defaults: { _controller: "AdministrationBundle:Ambiance:index" }
    methods:  GET

ambiance_show:
    path:     /{id}/show
    defaults: { _controller: "AdministrationBundle:Ambiance:show" }
    methods:  GET

ambiance_new:
    path:     /new
    defaults: { _controller: "AdministrationBundle:Ambiance:new" }
    methods:  [GET, POST]

ambiance_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdministrationBundle:Ambiance:edit" }
    methods:  [GET, POST]

ambiance_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdministrationBundle:Ambiance:delete" }
    methods:  DELETE
