saison_index:
    path:     /
    defaults: { _controller: "AdministrationBundle:Saison:index" }
    methods:  GET

saison_show:
    path:     /{id}/show
    defaults: { _controller: "AdministrationBundle:Saison:show" }
    methods:  GET

saison_new:
    path:     /new
    defaults: { _controller: "AdministrationBundle:Saison:new" }
    methods:  [GET, POST]

saison_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdministrationBundle:Saison:edit" }
    methods:  [GET, POST]

saison_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdministrationBundle:Saison:delete" }
    methods:  DELETE
